repos:
  - repo: https://github.com/kamadorueda/alejandra
    rev: d7552fef2ccf1bbf0d36b27f6fddb19073f205b7
    hooks:
      # Requires Nix to be previously installed in the system
      - id: alejandra-nix
